_nadia_simple_security_edit_user_roles:
    path: /nadia/simple-security/edit-user-roles/{firewallName}/{username}
    controller: Nadia\Bundle\NadiaSimpleSecurityBundle\Controller\EditUserRolesController:edit
    methods: [GET, POST]
