_nadia_simple_security_edit_roles:
    path: /nadia/simple-security/edit-user-roles/{firewallName}
    controller: Nadia\Bundle\NadiaSimpleSecurityBundle\Controller\EditRolesController:edit
    methods: [GET, POST]
