Nadia\Bundle\NadiaSimpleSecurityBundle\Model\Role:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        role:
            type: string
            length: 64
            unique: true
