parameters:

services:
    Nadia\Bundle\NadiaSimpleSecurityBundle\Controller\EditRolesController:
        arguments:
            - '@twig'
            - '@form.factory'
            - '@doctrine'
            - '@router'
            - '@nadia.simple_security.service_provider.role_management_config'
        public: true
