parameters:

services:
    Nadia\Bundle\NadiaSimpleSecurityBundle\Controller\EditRolesController:
        arguments:
            - '@twig'
            - '@form.factory'
            - '@doctrine'
            - '@router'
            - '@Nadia\Bundle\NadiaSimpleSecurityBundle\DependencyInjection\Container\ServiceProvider'
        public: true
