parameters:

services:
    Nadia\Bundle\NadiaSimpleSecurityBundle\DependencyInjection\Container\ServiceProvider:
        arguments:
            - ~

    Nadia\Bundle\NadiaSimpleSecurityBundle\Routing\Generator\EditRolesUrlGenerator:
        arguments:
            - '@router'
            - []

    Nadia\Bundle\NadiaSimpleSecurityBundle\Twig\Extension\RoutingExtension:
        arguments:
            - '@Nadia\Bundle\NadiaSimpleSecurityBundle\Routing\Generator\EditRolesUrlGenerator'
        tags:
            - { name: twig.extension }
